### ISSUE TITLE
make key for removing text area focus configurable

### ISSUE THREAD

**Issue by washtubs** [ardagnir/pterosaur#34]
Not sure if this was intended, but if you hit escape twice, it will exit the vim session requiring me to re-click on the textarea to continue typing. I doubt I'm the only person who has trained my hands to prefix various normal mode actions with a quick CTRL-[ to verify that I am in fact in normal mode. Ordinarily, this redundant keypress is inconsequential. But now it's a severe hindrance. Perhaps this could be configurable? I imagine making a custom mapping where something like <C-X> unfocuses the textarea and puts you back in browser mode would work pretty well.

Great job btw. I'll have you know I'm starting to switch back to firefox because of this. True embedded vim is worth the flash player woes in spades.

**Comment by jeaye** [comment]
I've also found that using escape to cancel commands (not related to VimFx) such a changing inside text objects ends up deselecting the text area.

Given text:
`(foo bar spam)`

Typing, in normal mode where the cursor is on, say, `b`:
`ci<ESC>`

Ends up, instead of cancelling the change, deselecting the text area.

**Comment by ardagnir** [comment]
@jeaye Escape always removes focus in normal mode. I'm pretty sure your bugs are duplicates of this one.

**Comment by ardagnir** [comment]
Fixed in version 1.1
